"""TRD §5.4 — WeasyPrint PDF renderer for the Carbon Action Plan.

The PDF is an explicitly downstream *rendering* of the same ActionPlan JSON the
API returns — one source of truth. The PDF and the in-product view are two
templates over the same object, not two independently maintained artifacts.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from string import Template

from services.reporting.models import ActionItem, ActionPlan

logger = logging.getLogger(__name__)

# Effort → colour mapping for the PDF badge
_EFFORT_COLOURS: dict[str, str] = {
    "Low": "#22c55e",
    "Medium": "#f59e0b",
    "High": "#ef4444",
}


def _escape_html(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


def _action_html(item: ActionItem) -> str:
    colour = _EFFORT_COLOURS.get(item.effort_level, "#6b7280")
    finding_refs = ", ".join(str(fid)[:8] + "…" for fid in item.justifying_finding_ids)
    return f"""
    <div class="action">
      <div class="action-header">
        <h3>{_escape_html(item.title)}</h3>
        <span class="badge"
              style="background:{colour}">{_escape_html(item.effort_level)} effort</span>
      </div>
      <p class="action-desc">{_escape_html(item.description)}</p>
      <table class="metrics">
        <tr>
          <th>CO₂ saved / yr</th>
          <th>Savings (INR / yr)</th>
          <th>Payback</th>
          <th>Finding ref</th>
        </tr>
        <tr>
          <td>{item.estimated_co2_saved_kg_per_year:,.0f} kg</td>
          <td>₹{item.estimated_savings_inr_per_year:,.0f}</td>
          <td>{item.payback_months:.0f} months</td>
          <td>{_escape_html(finding_refs)}</td>
        </tr>
      </table>
      <p class="confidence-note"><em>Confidence: {_escape_html(item.confidence_note)}</em></p>
    </div>"""


_HTML_TEMPLATE = Template("""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>CarbonSense — Carbon Action Plan</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
  body { font-family: Inter, sans-serif; margin: 40px; color: #1f2937; font-size: 13px; }
  h1 { color: #065f46; font-size: 22px; margin-bottom: 4px; }
  .meta { color: #6b7280; font-size: 11px; margin-bottom: 20px; }
  .summary-box { background: #f0fdf4; border-left: 4px solid #22c55e;
                 padding: 14px 18px; border-radius: 4px; margin-bottom: 24px; }
  .summary-box p { margin: 0; line-height: 1.6; }
  h2 { color: #047857; font-size: 15px; border-bottom: 1px solid #d1fae5;
       padding-bottom: 4px; margin-top: 28px; }
  .action { border: 1px solid #e5e7eb; border-radius: 6px;
            padding: 16px; margin-bottom: 16px; page-break-inside: avoid; }
  .action-header { display: flex; justify-content: space-between;
                   align-items: flex-start; margin-bottom: 8px; }
  .action-header h3 { margin: 0; font-size: 14px; color: #111827; }
  .badge { font-size: 10px; font-weight: 600; color: white;
           padding: 2px 8px; border-radius: 999px; white-space: nowrap; }
  .action-desc { color: #374151; margin: 0 0 10px; line-height: 1.5; }
  table.metrics { width: 100%; border-collapse: collapse; font-size: 11px; }
  table.metrics th { background: #f9fafb; padding: 4px 8px;
                     text-align: left; border: 1px solid #e5e7eb; color: #6b7280; }
  table.metrics td { padding: 4px 8px; border: 1px solid #e5e7eb; }
  .confidence-note { color: #6b7280; font-size: 11px; margin: 10px 0 0; }
  .footer { margin-top: 32px; color: #9ca3af; font-size: 10px;
            border-top: 1px solid #e5e7eb; padding-top: 8px; }
  .generated-by { display: inline-block; font-size: 10px; color: #9ca3af;
                  margin-top: 4px; }
</style>
</head>
<body>
<h1>CarbonSense — Carbon Action Plan</h1>
<p class="meta">Building: $building_name &nbsp;|&nbsp; Generated: $generated_at UTC</p>

<div class="summary-box">
  <p>$narrative_summary</p>
</div>

<h2>Recommended Actions</h2>
$actions_html

<div class="footer">
  <p>Generated by CarbonSense Explainability &amp; Reporting Service (TRD v2.0 §5)</p>
  <span class="generated-by">Source: $generated_by</span>
</div>
</body>
</html>""")


class PDFRenderer:
    """Renders a Carbon Action Plan PDF via WeasyPrint.

    The PDF consumes the IDENTICAL ActionPlan JSON the API returns — one source of
    truth (TRD v2.0 §5.4).
    """

    def render(self, action_plan: ActionPlan, building_name: str = "Building") -> bytes:
        """Render *action_plan* to PDF bytes.

        Args:
            action_plan:   The ActionPlan to render (from Narrator or FallbackNarrator).
            building_name: Displayed in the report header.

        Returns:
            PDF bytes (application/pdf).
        """
        from weasyprint import HTML  # lazy import — WeasyPrint is slow to import

        actions_html = "\n".join(_action_html(item) for item in action_plan.actions)
        if not actions_html:
            actions_html = "<p><em>No recommended actions at this time.</em></p>"

        html_str = _HTML_TEMPLATE.substitute(
            building_name=_escape_html(building_name),
            generated_at=datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M"),
            narrative_summary=_escape_html(action_plan.narrative_summary),
            actions_html=actions_html,
            generated_by=action_plan.generated_by,
        )

        logger.debug("PDFRenderer: rendering PDF for building %s", building_name)
        pdf_bytes: bytes = HTML(string=html_str).write_pdf()
        logger.info(
            "PDFRenderer: PDF rendered (%d bytes) for building %s",
            len(pdf_bytes),
            building_name,
        )
        return pdf_bytes
